// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "customPresets": string;
      "workspaceLayout": string;
      "iconPlacement": string;
      "itemPaneButtonEnabled": boolean;
      "maxContextBudget": number;
      "sidebarVisible": boolean;
      "evidenceEnabled": boolean;
      "evidenceProviderMode": string;
      "mcpEndpoint": string;
      "mcpToolName": string;
      "mcpToolArgumentsTemplate": string;
      "mcpAuthToken": string;
      "configSyncEnabled": boolean;
      "configSyncEndpoint": string;
      "configSyncRemotePath": string;
      "configSyncUsername": string;
      "configSyncPassword": string;
      "configSyncSnapshot": string;
      "themeMode": string;
      "defaultThinkingEffort": string;
      "selectionToolbarEnabled": boolean;
      "tokenDisplayEnabled": boolean;
      "quickPromptsEnabled": boolean;
      "selectionContextMode": string;
    };
  }
}
