// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "customPresets": string;
      "maxContextBudget": number;
      "sidebarVisible": boolean;
      "evidenceEnabled": boolean;
      "evidenceProviderMode": string;
      "mcpEndpoint": string;
      "mcpToolName": string;
      "mcpToolArgumentsTemplate": string;
      "mcpAuthToken": string;
    };
  }
}
